from pyspark.sql.types import (
    StructType,
    StructField,
    IntegerType,
    DoubleType,
    StringType,
    DateType
)

catalog_page_schema = StructType([
    StructField("cp_catalog_page_sk", IntegerType(), nullable=False),
    StructField("cp_catalog_page_id", StringType(), nullable=False),
    StructField("cp_start_date_sk", IntegerType(), True),
    StructField("cp_end_date_sk", IntegerType(), True),
    StructField("cp_department", StringType(), True),
    StructField("cp_catalog_number", IntegerType(), True),
    StructField("cp_catalog_page_number", IntegerType(), True),
    StructField("cp_description", StringType(), True),
    StructField("cp_type", StringType(), True)
])

call_center_schema = StructType([
    StructField("cc_call_center_sk", IntegerType(), nullable=False),
    StructField("cc_call_center_id", StringType(), nullable=False),
    StructField("cc_rec_start_date", DateType(), True),
    StructField("cc_rec_end_date", DateType(), True),
    StructField("cc_closed_date_sk", IntegerType(), True),
    StructField("cc_open_date_sk", IntegerType(), True),
    StructField("cc_name", StringType(), True),
    StructField("cc_class", StringType(), True),
    StructField("cc_employees", IntegerType(), True),
    StructField("cc_sq_ft", IntegerType(), True),
    StructField("cc_hours", StringType(), True),
    StructField("cc_manager", StringType(), True),
    StructField("cc_mkt_id", IntegerType(), True),
    StructField("cc_mkt_class", StringType(), True),
    StructField("cc_mkt_desc", StringType(), True),
    StructField("cc_market_manager", StringType(), True),
    StructField("cc_division", IntegerType(), True),
    StructField("cc_division_name", StringType(), True),
    StructField("cc_company", IntegerType(), True),
    StructField("cc_company_name", StringType(), True),
    StructField("cc_street_number", StringType(), True),
    StructField("cc_street_name", StringType(), True),
    StructField("cc_street_type", StringType(), True),
    StructField("cc_suite_number", StringType(), True),
    StructField("cc_city", StringType(), True),
    StructField("cc_county", StringType(), True),
    StructField("cc_state", StringType(), True),
    StructField("cc_zip", StringType(), True),
    StructField("cc_country", StringType(), True),
    StructField("cc_gmt_offset", DoubleType(), True),
    StructField("cc_tax_percentage", DoubleType(), True)
])

catalog_returns_schema = StructType([
    StructField("cr_returned_date_sk", IntegerType(), True),
    StructField("cr_returned_time_sk", IntegerType(), True),
    StructField("cr_item_sk", IntegerType(), nullable=False),
    StructField("cr_refunded_customer_sk", IntegerType(), True),
    StructField("cr_refunded_cdemo_sk", IntegerType(), True),
    StructField("cr_refunded_hdemo_sk", IntegerType(), True),
    StructField("cr_refunded_addr_sk", IntegerType(), True),
    StructField("cr_returning_customer_sk", IntegerType(), True),
    StructField("cr_returning_cdemo_sk", IntegerType(), True),
    StructField("cr_returning_hdemo_sk", IntegerType(), True),
    StructField("cr_returning_addr_sk", IntegerType(), True),
    StructField("cr_call_center_sk", IntegerType(), True),
    StructField("cr_catalog_page_sk", IntegerType(), True),
    StructField("cr_ship_mode_sk", IntegerType(), True),
    StructField("cr_warehouse_sk", IntegerType(), True),
    StructField("cr_reason_sk", IntegerType(), True),
    StructField("cr_order_number", IntegerType(), nullable=False),
    StructField("cr_return_quantity", IntegerType(), True),
    StructField("cr_return_amount", DoubleType(), True),
    StructField("cr_return_tax", DoubleType(), True),
    StructField("cr_return_amt_inc_tax", DoubleType(), True),
    StructField("cr_fee", DoubleType(), True),
    StructField("cr_return_ship_cost", DoubleType(), True),
    StructField("cr_refunded_cash", DoubleType(), True),
    StructField("cr_reversed_charge", DoubleType(), True),
    StructField("cr_store_credit", DoubleType(), True),
    StructField("cr_net_loss", DoubleType(), True)
])

catalog_sales_schema = StructType([
    StructField("cs_sold_date_sk", IntegerType(), True),
    StructField("cs_sold_time_sk", IntegerType(), True),
    StructField("cs_ship_date_sk", IntegerType(), True),
    StructField("cs_bill_customer_sk", IntegerType(), True),
    StructField("cs_bill_cdemo_sk", IntegerType(), True),
    StructField("cs_bill_hdemo_sk", IntegerType(), True),
    StructField("cs_bill_addr_sk", IntegerType(), True),
    StructField("cs_ship_customer_sk", IntegerType(), True),
    StructField("cs_ship_cdemo_sk", IntegerType(), True),
    StructField("cs_ship_hdemo_sk", IntegerType(), True),
    StructField("cs_ship_addr_sk", IntegerType(), True),
    StructField("cs_call_center_sk", IntegerType(), True),
    StructField("cs_catalog_page_sk", IntegerType(), True),
    StructField("cs_ship_mode_sk", IntegerType(), True),
    StructField("cs_warehouse_sk", IntegerType(), True),
    StructField("cs_item_sk", IntegerType(), nullable=False),
    StructField("cs_promo_sk", IntegerType(), True),
    StructField("cs_order_number", IntegerType(), nullable=False),
    StructField("cs_quantity", IntegerType(), True),
    StructField("cs_wholesale_cost", DoubleType(), True),
    StructField("cs_list_price", DoubleType(), True),
    StructField("cs_sales_price", DoubleType(), True),
    StructField("cs_ext_discount_amt", DoubleType(), True),
    StructField("cs_ext_sales_price", DoubleType(), True),
    StructField("cs_ext_wholesale_cost", DoubleType(), True),
    StructField("cs_ext_list_price", DoubleType(), True),
    StructField("cs_ext_tax", DoubleType(), True),
    StructField("cs_coupon_amt", DoubleType(), True),
    StructField("cs_ext_ship_cost", DoubleType(), True),
    StructField("cs_net_paid", DoubleType(), True),
    StructField("cs_net_paid_inc_tax", DoubleType(), True),
    StructField("cs_net_paid_inc_ship", DoubleType(), True),
    StructField("cs_net_paid_inc_ship_tax", DoubleType(), True),
    StructField("cs_net_profit", DoubleType(), True)
])

customer_schema = StructType([
    StructField("c_customer_sk", IntegerType(), nullable=False),
    StructField("c_customer_id", StringType(), nullable=False),
    StructField("c_current_cdemo_sk", IntegerType(), True),
    StructField("c_current_hdemo_sk", IntegerType(), True),
    StructField("c_current_addr_sk", IntegerType(), True),
    StructField("c_first_shipto_date_sk", IntegerType(), True),
    StructField("c_first_sales_date_sk", IntegerType(), True),
    StructField("c_salutation", StringType(), True),
    StructField("c_first_name", StringType(), True),
    StructField("c_last_name", StringType(), True),
    StructField("c_preferred_cust_flag", StringType(), True),
    StructField("c_birth_day", IntegerType(), True),
    StructField("c_birth_month", IntegerType(), True),
    StructField("c_birth_year", IntegerType(), True),
    StructField("c_birth_country", StringType(), True),
    StructField("c_login", StringType(), True),
    StructField("c_email_address", StringType(), True),
    StructField("c_last_review_date", StringType(), True),
])

customer_address_schema = StructType([
    StructField("ca_address_sk", IntegerType(), nullable=False),
    StructField("ca_address_id", StringType(), nullable=False),
    StructField("ca_street_number", StringType(), True),
    StructField("ca_street_name", StringType(), True),
    StructField("ca_street_type", StringType(), True),
    StructField("ca_suite_number", StringType(), True),
    StructField("ca_city", StringType(), True),
    StructField("ca_county", StringType(), True),
    StructField("ca_state", StringType(), True),
    StructField("ca_zip", StringType(), True),
    StructField("ca_country", StringType(), True),
    StructField("ca_gmt_offset", DoubleType(), True),
    StructField("ca_location_type", StringType(), True)
])

customer_demographics_schema = StructType([
    StructField("cd_demo_sk", IntegerType(), nullable=False),
    StructField("cd_gender", StringType(), True),
    StructField("cd_marital_status", StringType(), True),
    StructField("cd_education_status", StringType(), True),
    StructField("cd_purchase_estimate", IntegerType(), True),
    StructField("cd_credit_rating", StringType(), True),
    StructField("ca_city", IntegerType(), True),
    StructField("cd_dep_employed_count", IntegerType(), True),
    StructField("cd_dep_college_count", IntegerType(), True)
])

date_dim_schema = StructType([
    StructField("d_date_sk", IntegerType(), nullable=False),
    StructField("d_date_id", StringType(), nullable=False),
    StructField("d_date", DateType(), True),
    StructField("d_month_seq", IntegerType(), True),
    StructField("d_week_seq", IntegerType(), True),
    StructField("d_quarter_seq", IntegerType(), True),
    StructField("d_year", IntegerType(), True),
    StructField("d_dow", IntegerType(), True),
    StructField("d_moy", IntegerType(), True),
    StructField("d_dom", IntegerType(), True),
    StructField("d_qoy", IntegerType(), True),
    StructField("d_fy_year", IntegerType(), True),
    StructField("d_fy_quarter_seq", IntegerType(), True),
    StructField("d_fy_week_seq", IntegerType(), True),
    StructField("d_day_name", StringType(), True),
    StructField("d_quarter_name", StringType(), True),
    StructField("d_holiday", StringType(), True),
    StructField("d_weekend", StringType(), True),
    StructField("d_following_holiday", StringType(), True),
    StructField("d_first_dom", IntegerType(), True),
    StructField("d_last_dom", IntegerType(), True),
    StructField("d_same_day_ly", IntegerType(), True),
    StructField("d_same_day_lq", IntegerType(), True),
    StructField("d_current_day", StringType(), True),
    StructField("d_current_week", StringType(), True),
    StructField("d_current_month", StringType(), True),
    StructField("d_current_quarter", StringType(), True),
    StructField("d_current_year", StringType(), True)
])

dbgen_version_schema = StructType([
    StructField("dv_version", StringType(), True),
    StructField("dv_create_date", DateType(), True),
    StructField("dv_create_time", StringType(), True),
    StructField("dv_cmdline_args", StringType(), True)
])

household_demographics_schema = StructType([
    StructField("hd_demo_sk", IntegerType(), nullable=False),
    StructField("hd_income_band_sk", IntegerType(), True),
    StructField("hd_buy_potential", StringType(), True),
    StructField("hd_dep_count", IntegerType(), True),
    StructField("hd_vehicle_count", IntegerType(), True)
])

income_band_schema = StructType([
    StructField("ib_income_band_sk", IntegerType(), nullable=False),
    StructField("ib_lower_bound", IntegerType(), True),
    StructField("ib_upper_bound", IntegerType(), True)
])

inventory_schema = StructType([
    StructField("inv_date_sk", IntegerType(), nullable=False),
    StructField("inv_item_sk", IntegerType(), nullable=False),
    StructField("inv_warehouse_sk", IntegerType(), nullable=False),
    StructField("inv_quantity_on_hand", IntegerType(), True),
])

item_schema = StructType([
    StructField("i_item_sk", IntegerType(), nullable=False),
    StructField("i_item_id", StringType(), nullable=False),
    StructField("i_rec_start_date", DateType(), True),
    StructField("i_rec_end_date", DateType(), True),
    StructField("i_item_desc", StringType(), True),
    StructField("i_current_price", DoubleType(), True),
    StructField("i_wholesale_cost", DoubleType(), True),
    StructField("i_brand_id", IntegerType(), True),
    StructField("i_brand", StringType(), True),
    StructField("i_class_id", IntegerType(), True),
    StructField("i_class", StringType(), True),
    StructField("i_category_id", IntegerType(), True),
    StructField("i_category", StringType(), True),
    StructField("i_manufact_id", IntegerType(), True),
    StructField("i_manufact", StringType(), True),
    StructField("i_size", StringType(), True),
    StructField("i_formulation", StringType(), True),
    StructField("i_color", StringType(), True),
    StructField("i_units", StringType(), True),
    StructField("i_container", StringType(), True),
    StructField("i_manager_id", IntegerType(), True),
    StructField("i_product_name", StringType(), True)
])

promotion_schema = StructType([
    StructField("p_promo_sk", IntegerType(), nullable=False),
    StructField("p_promo_id", StringType(), nullable=False),
    StructField("p_start_date_sk", IntegerType(), True),
    StructField("p_end_date_sk", IntegerType(), True),
    StructField("p_item_sk", IntegerType(), True),
    StructField("p_cost", DoubleType(), True),
    StructField("p_response_target", IntegerType(), True),
    StructField("p_promo_name", StringType(), True),
    StructField("p_channel_dmail", StringType(), True),
    StructField("p_channel_email", StringType(), True),
    StructField("p_channel_catalog", StringType(), True),
    StructField("p_channel_tv", StringType(), True),
    StructField("p_channel_radio", StringType(), True),
    StructField("p_channel_press", StringType(), True),
    StructField("p_channel_event", StringType(), True),
    StructField("p_channel_demo", StringType(), True),
    StructField("p_channel_details", StringType(), True),
    StructField("p_purpose", StringType(), True),
    StructField("p_discount_active", StringType(), True)
])

reason_schema = StructType([
    StructField("r_reason_sk", IntegerType(), nullable=False),
    StructField("r_reason_id", StringType(), nullable=False),
    StructField("r_reason_desc", StringType(), True)
])

ship_mode_schema = StructType([
    StructField("sm_ship_mode_sk", IntegerType(), nullable=False),
    StructField("sm_ship_mode_id", StringType(), nullable=False),
    StructField("sm_type", StringType(), True),
    StructField("sm_code", StringType(), True),
    StructField("sm_carrier", StringType(), True),
    StructField("sm_contract", StringType(), True)
])

store_schema = StructType([
    StructField("s_store_sk", IntegerType(), nullable=False),
    StructField("s_store_id", StringType(), nullable=False),
    StructField("s_rec_start_date", DateType(), True),
    StructField("s_rec_end_date", DateType(), True),
    StructField("s_closed_date_sk", IntegerType(), True),
    StructField("s_store_name", StringType(), True),
    StructField("s_number_employees", IntegerType(), True),
    StructField("s_floor_space", IntegerType(), True),
    StructField("s_hours", StringType(), True),
    StructField("s_manager", StringType(), True),
    StructField("s_market_id", IntegerType(), True),
    StructField("s_geography_class", StringType(), True),
    StructField("s_market_desc", StringType(), True),
    StructField("s_market_manager", StringType(), True),
    StructField("s_division_id", IntegerType(), True),
    StructField("s_division_name", StringType(), True),
    StructField("s_company_id", IntegerType(), True),
    StructField("s_company_name", StringType(), True),
    StructField("s_street_number", StringType(), True),
    StructField("s_street_name", StringType(), True),
    StructField("s_street_type", StringType(), True),
    StructField("s_suite_number", StringType(), True),
    StructField("s_city", StringType(), True),
    StructField("s_county", StringType(), True),
    StructField("s_state", StringType(), True),
    StructField("s_zip", StringType(), True),
    StructField("s_country", StringType(), True),
    StructField("s_gmt_offset", DoubleType(), True),
    StructField("s_tax_precentage", DoubleType(), True)
])

store_returns_schema = StructType([
    StructField("sr_returned_date_sk", IntegerType(), True),
    StructField("sr_return_time_sk", IntegerType(), True),
    StructField("sr_item_sk", IntegerType(), nullable=False),
    StructField("sr_customer_sk", IntegerType(), True),
    StructField("sr_cdemo_sk", IntegerType(), True),
    StructField("sr_hdemo_sk", IntegerType(), True),
    StructField("sr_addr_sk", IntegerType(), True),
    StructField("sr_store_sk", IntegerType(), True),
    StructField("sr_reason_sk", IntegerType(), True),
    StructField("sr_ticket_number", IntegerType(), nullable=False),
    StructField("sr_return_quantity", IntegerType(), True),
    StructField("sr_return_amt", DoubleType(), True),
    StructField("sr_return_tax", DoubleType(), True),
    StructField("sr_return_amt_inc_tax", DoubleType(), True),
    StructField("sr_fee", DoubleType(), True),
    StructField("sr_return_ship_cost", DoubleType(), True),
    StructField("sr_refunded_cash", DoubleType(), True),
    StructField("sr_reversed_charge", DoubleType(), True),
    StructField("sr_store_credit", DoubleType(), True),
    StructField("sr_net_loss", DoubleType(), True)
])

store_sales_schema = StructType([
    StructField("ss_sold_date_sk", IntegerType(), True),
    StructField("ss_sold_time_sk", IntegerType(), True),
    StructField("ss_item_sk", IntegerType(), nullable=False),
    StructField("ss_customer_sk", IntegerType(), True),
    StructField("ss_cdemo_sk", IntegerType(), True),
    StructField("ss_hdemo_sk", IntegerType(), True),
    StructField("ss_addr_sk", IntegerType(), True),
    StructField("ss_store_sk", IntegerType(), True),
    StructField("ss_promo_sk", IntegerType(), True),
    StructField("ss_ticket_number", IntegerType(), nullable=False),
    StructField("ss_quantity", IntegerType(), True),
    StructField("ss_wholesale_cost", DoubleType(), True),
    StructField("ss_list_price", DoubleType(), True),
    StructField("ss_sales_price", DoubleType(), True),
    StructField("ss_ext_discount_amt", DoubleType(), True),
    StructField("ss_ext_sales_price", DoubleType(), True),
    StructField("ss_ext_wholesale_cost", DoubleType(), True),
    StructField("ss_ext_list_price", DoubleType(), True),
    StructField("ss_ext_tax", DoubleType(), True),
    StructField("ss_coupon_amt", DoubleType(), True),
    StructField("ss_net_paid", DoubleType(), True),
    StructField("ss_net_paid_inc_tax", DoubleType(), True),
    StructField("ss_net_profit", DoubleType(), True)
])

time_dim_schema = StructType([
    StructField("t_time_sk", IntegerType(), nullable=False),
    StructField("t_time_id", StringType(), nullable=False),
    StructField("t_time", IntegerType(), True),
    StructField("t_hour", IntegerType(), True),
    StructField("t_minute", IntegerType(), True),
    StructField("t_second", IntegerType(), True),
    StructField("t_am_pm", StringType(), True),
    StructField("t_shift", StringType(), True),
    StructField("t_sub_shift", StringType(), True),
    StructField("t_meal_time", StringType(), True)
])

warehouse_schema = StructType([
    StructField("w_warehouse_sk", IntegerType(), nullable=False),
    StructField("w_warehouse_id", StringType(), nullable=False),
    StructField("w_warehouse_name", StringType(), True),
    StructField("w_warehouse_sq_ft", IntegerType(), True),
    StructField("w_street_number", StringType(), True),
    StructField("w_street_name", StringType(), True),
    StructField("w_street_type", StringType(), True),
    StructField("w_suite_number", StringType(), True),
    StructField("w_city", StringType(), True),
    StructField("w_county", StringType(), True),
    StructField("w_state", StringType(), True),
    StructField("w_zip", StringType(), True),
    StructField("w_country", StringType(), True),
    StructField("w_gmt_offset", DoubleType(), True)
])

web_page_schema = StructType([
    StructField("wp_web_page_sk", IntegerType(), nullable=False),
    StructField("wp_web_page_id", StringType(), nullable=False),
    StructField("wp_rec_start_date", DateType(), True),
    StructField("wp_rec_end_date", DateType(), True),
    StructField("wp_creation_date_sk", IntegerType(), True),
    StructField("wp_access_date_sk", IntegerType(), True),
    StructField("wp_autogen_flag", StringType(), True),
    StructField("wp_customer_sk", IntegerType(), True),
    StructField("wp_url", StringType(), True),
    StructField("wp_type", StringType(), True),
    StructField("wp_char_count", IntegerType(), True),
    StructField("wp_link_count", IntegerType(), True),
    StructField("wp_image_count", IntegerType(), True),
    StructField("wp_max_ad_count", IntegerType(), True)
])

web_returns_schema = StructType([
    StructField("wr_returned_date_sk", IntegerType(), True),
    StructField("wr_returned_time_sk", IntegerType(), True),
    StructField("wr_item_sk", IntegerType(), nullable=False),
    StructField("wr_refunded_customer_sk", IntegerType(), True),
    StructField("wr_refunded_cdemo_sk", IntegerType(), True),
    StructField("wr_refunded_hdemo_sk", IntegerType(), True),
    StructField("wr_refunded_addr_sk", IntegerType(), True),
    StructField("wr_returning_customer_sk", IntegerType(), True),
    StructField("wr_returning_cdemo_sk", IntegerType(), True),
    StructField("wr_returning_hdemo_sk", IntegerType(), True),
    StructField("wr_returning_addr_sk", IntegerType(), True),
    StructField("wr_web_page_sk", IntegerType(), True),
    StructField("wr_reason_sk", IntegerType(), True),
    StructField("wr_order_number", IntegerType(), nullable=False),
    StructField("wr_return_quantity", IntegerType(), True),
    StructField("wr_return_amt", DoubleType(), True),
    StructField("wr_return_tax", DoubleType(), True),
    StructField("wr_return_amt_inc_tax", DoubleType(), True),
    StructField("wr_fee", DoubleType(), True),
    StructField("wr_return_ship_cost", DoubleType(), True),
    StructField("wr_refunded_cash", DoubleType(), True),
    StructField("wr_reversed_charge", DoubleType(), True),
    StructField("wr_account_credit", DoubleType(), True),
    StructField("wr_net_loss", DoubleType(), True)
])

web_sales_schema = StructType([
    StructField("ws_sold_date_sk", IntegerType(), True),
    StructField("ws_sold_time_sk", IntegerType(), True),
    StructField("ws_ship_date_sk", IntegerType(), True),
    StructField("ws_item_sk", IntegerType(), nullable=False),
    StructField("ws_bill_customer_sk", IntegerType(), True),
    StructField("ws_bill_cdemo_sk", IntegerType(), True),
    StructField("ws_bill_hdemo_sk", IntegerType(), True),
    StructField("ws_bill_addr_sk", IntegerType(), True),
    StructField("ws_ship_customer_sk", IntegerType(), True),
    StructField("ws_ship_cdemo_sk", IntegerType(), True),
    StructField("ws_ship_hdemo_sk", IntegerType(), True),
    StructField("ws_ship_addr_sk", IntegerType(), True),
    StructField("ws_web_page_sk", IntegerType(), True),
    StructField("ws_web_site_sk", IntegerType(), True),
    StructField("ws_ship_mode_sk", IntegerType(), True),
    StructField("ws_warehouse_sk", IntegerType(), True),
    StructField("ws_promo_sk", IntegerType(), True),
    StructField("ws_order_number", IntegerType(), nullable=False),
    StructField("ws_quantity", DoubleType(), True),
    StructField("ws_wholesale_cost", DoubleType(), True),
    StructField("ws_list_price", DoubleType(), True),
    StructField("ws_sales_price", DoubleType(), True),
    StructField("ws_ext_discount_amt", DoubleType(), True),
    StructField("ws_ext_sales_price", DoubleType(), True),
    StructField("ws_ext_wholesale_cost", DoubleType(), True),
    StructField("ws_ext_list_price", DoubleType(), True),
    StructField("ws_ext_tax", DoubleType(), True),
    StructField("ws_coupon_amt", DoubleType(), True),
    StructField("ws_ext_ship_cost", DoubleType(), True),
    StructField("ws_net_paid", DoubleType(), True),
    StructField("ws_net_paid_inc_tax", DoubleType(), True),
    StructField("ws_net_paid_inc_ship", DoubleType(), True),
    StructField("ws_net_paid_inc_ship_tax", DoubleType(), True),
    StructField("ws_net_profit", DoubleType(), True)
])

web_site_schema = StructType([
    StructField("web_site_sk", IntegerType(),  nullable=False),
    StructField("web_site_id", StringType(),  nullable=False),
    StructField("web_rec_start_date", DateType(), True),
    StructField("web_rec_end_date", DateType(), True),
    StructField("web_name", StringType(), True),
    StructField("web_open_date_sk", IntegerType(), True),
    StructField("web_close_date_sk", IntegerType(), True),
    StructField("web_class", StringType(), True),
    StructField("web_manager", StringType(), True),
    StructField("web_mkt_id", IntegerType(), True),
    StructField("web_mkt_class", StringType(), True),
    StructField("web_mkt_desc", StringType(), True),
    StructField("web_market_manager", StringType(), True),
    StructField("web_company_id", IntegerType(), True),
    StructField("web_company_name", StringType(), True),
    StructField("web_street_number", StringType(), True),
    StructField("web_street_name", StringType(), True),
    StructField("web_street_type", StringType(), True),
    StructField("web_suite_number", StringType(), True),
    StructField("web_city", StringType(), True),
    StructField("web_county", StringType(), True),
    StructField("web_state", StringType(), True),
    StructField("web_zip", StringType(), True),
    StructField("web_country", StringType(), True),
    StructField("web_gmt_offset", DoubleType(), True),
    StructField("web_tax_percentage", DoubleType(), True)
])
